services:
  - type: static
    name: department-management-frontend
    env: node
    buildCommand: |
      npm ci
      npm run build
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_OPTIONS
        value: --max_old_space_size=4096
    staticPublishPath: ./dist/user-management-system 