services:
  - type: web
    name: department-management-frontend
    env: node
    buildCommand: |
      npm install
      npm install -g @angular/cli@17.3.10
      export PATH=$PATH:$(npm config get prefix)/bin
      ng build --configuration production
    startCommand: ng serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.x
      - key: PATH
        value: $PATH:$(npm config get prefix)/bin
    staticPublishPath: ./dist/angular-signup-verification-boilerplate 