services:
  # Backend API Service
  - type: web
    name: final-intprog-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && node server.js
    publishDir: Backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false

  # Frontend Service
  - type: web
    name: final-intprog-web
    env: node
    region: oregon
    plan: free
    buildCommand: |
      cd Frontend && \
      npm install && \
      npm install -g @angular/cli && \
      ng build --configuration production
    startCommand: cd Frontend && ng serve --configuration production --host 0.0.0.0 --port $PORT
    publishDir: Frontend/dist/user-management-system
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://final-intprog-api.onrender.com
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 18.13.0 