services:
  # Backend API Service
  - type: web
    name: final-intprog-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && node server.js
    publishDir: Backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false

  # Frontend Service
  - type: web
    name: final-intprog-frontend
    env: static
    buildCommand: |
      cd Frontend
      npm install
      npm install -g @angular/cli@17.3.10
      export PATH=$PATH:$(npm config get prefix)/bin
      ng build --configuration production --base-href=/ --output-path=dist/final-intprog
    staticPublishPath: Frontend/dist/final-intprog
    envVars:
      - key: API_URL
        value: https://final-intprog-k6j8.onrender.com
      - key: ENVIRONMENT
        value: production
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_OPTIONS
        value: --max_old_space_size=4096
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*
        name: Pragma
        value: no-cache
      - path: /*
        name: Expires
        value: "0"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
