services:
  - type: web
    name: final-intprog
    env: node
    buildCommand: |
      cd Frontend
      rm -rf dist
      rm -rf node_modules
      npm install
      npm run build
      cd ../Backend
      npm install
    startCommand: node Backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 10000
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*
        name: Pragma
        value: no-cache
      - path: /*
        name: Expires
        value: 0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      - type: rewrite
        source: /assets/*
        destination: /assets/* 