services:
  - type: web
    name: final-intprog-frontend
    env: static
    buildCommand: |
      cd Frontend
      npm install
      npm run build
    staticPublishPath: Frontend/dist/final-intprog
    envVars:
      - key: NODE_VERSION
        value: 18.x
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*
        name: Pragma
        value: no-cache
      - path: /*
        name: Expires
        value: 0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      - type: rewrite
        source: /assets/*
        destination: /assets/* 