services:
  - type: web
    name: department-management-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: 153.92.15.31
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: u875409848_purisima
      - key: DB_PASSWORD
        value: 9T2Z5$3UKkgSYzE
      - key: DB_NAME
        value: u875409848_purisima
      - key: JWT_SECRET
        value: terces
      - key: CORS_ORIGINS
        value: https://department-management-frontend.onrender.com
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0" 